name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # ðŸ”“ Open port 22 to 0.0.0.0/0 temporarily
      - name: Temporarily open port 22 to 0.0.0.0/0
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr 0.0.0.0/0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Deploy and run Docker
      - name: Deploy to EC2 with Docker
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "GOOGLE_BOOKS_API_KEY=${{ secrets.GOOGLE_BOOKS_API_KEY }} USER_NAME=${{ secrets.USER_NAME}} bash -s" << 'EOF'
            
            set -e
              
            mkdir -p ${{ secrets.APP_DIR }}
            cd ${{ secrets.APP_DIR }}

            if [ ! -d .git ]; then
              git clone git@github.com:KevinHenleyCode/Book-Library.git .
            fi

            git pull origin main

            rm -rf node_modules .next

            # Stop and remove old container if it exists
            docker stop book-library || true
            docker rm book-library || true

            # Clean up old images of book-library only
            docker images -q book-library | xargs -r docker rmi

            # Remove dangling images
            docker image prune -f

            # Check if pnpm-store exists
            docker volume create pnpm-store || true

            # Build and run new Docker Container
            docker build --no-cache -t book-library .
            
            docker run -d --name book-library \
              --env GOOGLE_BOOKS_API_KEY=$GOOGLE_BOOKS_API_KEY \
              --env USER_NAME=$USER_NAME \
              -v pnpm-store:/pnpm-store \
              -p 127.0.0.1:3001:3000 --restart unless-stopped book-library
          EOF

      # ðŸ”’ Revoke open SSH access after deployment
      - name: Lock down port 22 again
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr 0.0.0.0/0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
